---
- name: Installation de wir3lss
  hosts: webserver
  become: yes

  vars_files:
    - prod/main.yml
  roles:
    - geerlingguy.php
    - geerlingguy.composer
    - ocha.yarn

  tasks:
  - name: Installation de Nginx
    block:
      - name: Update
        apt: update_cache=yes
      - name: Installation de Nginx
        apt:
          name: nginx
          state: latest
        notify: restart nginx

  - name: Application droit www-data
    command: chown www-data:www-data /var/www/html

  - name: Deploiement du code depuis GitHub
    block:
      - name: Copie du source code
        git:
          repo: git@github.com:leodelmas/wir3lss.git
          version: master
          dest: /var/www/html 
          accept_hostkey: yes
          force: yes

  handlers:
        - import_tasks: handlers/main.yml 
