---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    shell: hostname
    register: show

  - name: Show hostname
    debug: msg="{{ show.stdout }}"


