---
- name: Installation de wir3lss
  hosts: webserver
  become: yes

  vars_files:
    - prod/main.yml
    - prod/env.vault.yml
    - prod/mysql.vault.yml
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.composer
    #Comment temporaire
    #- ocha.yarn
    - geerlingguy.mysql

  pre_tasks:
  - name : check yarn installation
    apt:
       name: 
        - yarn
       state: present
       update_cache: yes

  post_tasks:
  - name: Application droit webserver
    command: chown root:root /var/www/html -R

  - name: Deploiement du code depuis GitHub
    block:
      - name: Copie du source code
        git:
          repo: git@github.com:leodelmas/wir3lss.git
          version: master
          dest: /var/www/html 
          accept_hostkey: yes
          force: yes
      - name: Copie .env
        template:
          src: "templates/.env.j2"
          dest: "/var/www/html/.env"
          mode: 0644
      - name: Application droit www-data
        command: chown www-data:www-data /var/www/html -R
      - name: Installation dépendance composer
        shell: cd /var/www/html && echo yes | composer install
      - name: Installation de yarm
        shell: cd /var/www/html/assets && sudo yarn install
      - name: Build yarn
        shell: cd /var/www/html && sudo yarn run build
      - name: Application droit www-data
        command: chown www-data:www-data /var/www/html -R

  - name: Configure php/console Symfony
    block:
      - name: database configure
        shell: cd /var/www/html && php bin/console d:d:c --if-not-exists
      - name: database migration
        shell: cd /var/www/html && echo yes | php bin/console d:m:m

  handlers:
        - import_tasks: handlers/main.yml 
