# PHP
php_default_version_debian: "8.0"
php_enable_php_fpm: true
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_webserver_daemon: "nginx"
php_packages:
  - php
  - php-cli
  - php-common
  - php-gd
  - php-mbstring
  - php-pdo
  - php-xml
