name: Deploy wir3lss web

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: install_wir3lss.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            wir3lss-webserver.duckdns.org
          requirements: requirements.yml
          options: |
            --inventory hosts
